apiVersion: v1
kind: ConfigMap
metadata:
  name: foo
data:
    FOO: bar
---
apiVersion: v1
kind: Pod
metadata:
  name: tomcat
spec:
  containers:
  - name: app
    image: docker.io/tomcat:9.0
    envFrom:
    - configMapRef:
        name: foo
        optional: false
    ports:
    - containerPort: 8080